"""empty message

Revision ID: 308321ba89a2
Revises: 4c15066f3229
Create Date: 2022-06-02 19:06:54.313783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308321ba89a2'
down_revision = '4c15066f3229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
